### ISSUE TITLE
Unauthorized Reply from Server

### ISSUE THREAD

**Issue by ecdarreola** [secretdataz/athena-web-service#4]
I have successfully upload and download emblem and it's showing on my client.

However, it doesn't work for other player or users. Is this because of same_ip config? It's true by default.

**Comment by secretdataz** [comment]
Did you manage to resolve this issue? If not, what have you tried so far?

**Comment by ecdarreola** [comment]
Yes managed to solve the issue by reverting the commit for https://github.com/secretdataz/athena-web-service/commit/2a3a3e73e86c596e6fb5c3d15bf41fb819e5b278

**Comment by secretdataz** [comment]
@ecdarreola Have you tried changing the value of `ATHENA_FORCE_SAME_IP` in `.env` to false?

**Comment by ecdarreola** [comment]
Yes I did and didn't work also when changing it to false at .env

It only shows on my client but not on other players.

**Comment by secretdataz** [comment]
Alright, thanks for the feedback :)
