### ISSUE TITLE
Some questions would like to ask!

### ISSUE THREAD

**Issue by 24msz6eo** [secretdataz/athena-web-service#8]
Excuse me, I would like to ask, besides modifying the two files of .env and athena.php, what else needs to be modified?
And rathena, do you need to make any changes?

**Comment by ecdarreola** [comment]
No changes needed in rAthena.

.env and athena.php is enough for setting up web-services and make sure permission are correctly set to storage folder.

Assuming you did all correctly in your rAthena :D

**Comment by 24msz6eo** [comment]
How can I solve this problem?
![1595830557939](https://user-images.githubusercontent.com/68574321/88509488-c4a00980-d013-11ea-9260-faf400ddfa78.jpg)
